/**
 * CheckpointService — 检查点服务 / Checkpoint Service
 *
 * 构建和保存 checkpoint，实现"双轨 checkpoint"的 mechanical 轨。
 * Builds and persists checkpoints, implementing the "dual-track checkpoint" mechanical track.
 *
 * [WHY] Checkpoint 是记忆引擎的核心持久化单元。Mechanical checkpoint 不依赖 LLM，
 * 纯粹从消息流和状态中机械提取关键信息；Summary checkpoint（Phase 2）由 LLM 生成。
 * Checkpoint is the core persistence unit of the memory engine. Mechanical checkpoint
 * does not depend on LLM — it mechanically extracts key info from message stream and state;
 * Summary checkpoint (Phase 2) is generated by LLM.
 *
 * @module checkpoint-service
 * @author DEEP-IOS
 */

import { saveCheckpoint } from "../../layer1-core/db.js";
import { extractMessageText, extractToolCalls, truncate } from "../../layer1-core/message-utils.js";

/**
 * 构建 Mechanical Checkpoint
 * Build Mechanical Checkpoint
 *
 * 这是"双轨 checkpoint"的第一轨，不依赖 LLM
 * This is the first track of the "dual-track checkpoint", LLM-independent
 *
 * @param {object} state      - agent 内存状态 / agent in-memory state
 * @param {Array}  [messages] - session 消息（可选，来自 agent_end）/ session messages (optional, from agent_end)
 * @param {object} config     - 全局配置 / global config
 * @returns {object}
 */
export function buildMechanicalCheckpoint(state, messages, config) {
  // 如果有完整 messages（来自 agent_end），优先从中提取
  // If full messages are available (from agent_end), extract from them first
  if (messages && Array.isArray(messages) && messages.length > 0) {
    return buildFromMessages(messages, state, config);
  }

  // 否则从内存状态构建 / Otherwise build from in-memory state
  return buildFromState(state, config);
}

/**
 * 从消息数组构建 checkpoint / Build checkpoint from message array
 */
function buildFromMessages(messages, state, config) {
  const recentMsgs = [];
  const recentTools = [];
  const modFiles = new Set(state?.modifiedFiles || []);
  let lastUserMsg = "";

  for (const msg of messages) {
    if (!msg || typeof msg !== "object") continue;

    const role = msg.role;
    const text = extractMessageText(msg);

    // 用户消息 / User message
    if (role === "user" && text && !text.startsWith("/")) {
      lastUserMsg = text;
      recentMsgs.push({
        role: "user",
        content: truncate(text, config.maxMsgChars),
      });
    }
    // 助手消息 / Assistant message
    else if (role === "assistant" && text) {
      recentMsgs.push({
        role: "assistant",
        content: truncate(text, config.maxMsgChars),
      });

      // 提取工具调用 / Extract tool calls
      const tools = extractToolCalls(msg);
      for (const tool of tools) {
        recentTools.push({
          name: tool.name,
          params: truncate(tool.params, 200),
          ts: Date.now(),
        });
      }
    }
    // 工具结果 / Tool result
    else if (role === "tool" && recentTools.length > 0) {
      const result = truncate(extractMessageText(msg), 300);
      const lastTool = recentTools[recentTools.length - 1];
      if (!lastTool.result) {
        lastTool.result = result;
      }
    }
  }

  return {
    recent_messages: recentMsgs.slice(-config.maxRecentMsgs * 2),
    recent_tool_calls: recentTools.slice(-config.maxRecentTools),
    modified_files: [...modFiles].slice(-config.maxModifiedFiles),
    last_user_message: truncate(lastUserMsg, config.maxMsgChars),
    turn_count: state?.turnCount || 0,
    timestamp: Date.now(),
  };
}

/**
 * 从内存状态构建 checkpoint / Build checkpoint from in-memory state
 */
function buildFromState(state, config) {
  return {
    recent_messages: (state?.recentMessages || []).slice(-config.maxRecentMsgs * 2),
    recent_tool_calls: (state?.recentToolCalls || []).slice(-config.maxRecentTools),
    modified_files: [...(state?.modifiedFiles || [])].slice(-config.maxModifiedFiles),
    last_user_message: truncate(state?.lastUserMessage || "", config.maxMsgChars),
    turn_count: state?.turnCount || 0,
    timestamp: Date.now(),
  };
}

/**
 * 保存 checkpoint 到数据库 / Persist checkpoint to database
 *
 * @param {string} agentId    - agent 标识 / agent identifier
 * @param {string} sessionId  - 会话 ID / session ID
 * @param {string} trigger    - 触发原因 / trigger reason
 * @param {object} state      - 内存状态 / in-memory state
 * @param {Array}  [messages] - 消息（可选）/ messages (optional)
 * @param {object} summary    - LLM 摘要（可选，Phase 2）/ LLM summary (optional, Phase 2)
 * @param {object} config     - 全局配置 / global config
 * @returns {string} checkpoint ID
 */
export function persistCheckpoint(agentId, sessionId, trigger, state, messages, summary, config) {
  const mechanical = buildMechanicalCheckpoint(state, messages, config);

  return saveCheckpoint({
    agentId,
    sessionId: sessionId || "unknown",
    trigger,
    mechanical,
    summary,
  });
}
